name = "Zhuia"
description = "An elegant but still playful theme for Zola."
license = "MIT"
homepage = "https://github.com/gicrisf/zhuia"
min_version = "0.15.0"
demo = "https://zhuia.netlify.app"
created=2021-06-30
updated=2022-03-07

[author]
name = "Giovanni Crisalfi"
homepage = "https://github.com/gicrisf"
